config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  resources :groups, only: [:index, :create, :show, :update, :destroy]
  resources :tasks, only: [:index, :create, :show, :update, :destroy] do
    resources :finishes, only: [:create, :destroy]
  end
  resources :messages, only: [:new, :create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/finish.rb
class Finish < ApplicationRecord
  belongs_to :task
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :group_name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :message, presence: true
  validates :speaker, presence: true
  validates :message_type, presence: true
end

app/models/prioritiy.rb
class Prioritiy < ApplicationRecord

  belongs_to :task

  validates :weight, presence: true
end

app/models/priority.rb
class Priority < ApplicationRecord

  belongs_to :task

  validates :weight, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :group
  has_one :priority, dependent: :destroy
  has_one :finish, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :type

  validates :content, presence: true
  validates :type_id, numericality: { other_than: 1 }
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '家事' },
    { id: 3, name: '買い物' },
    { id: 4, name: '趣味' },
    { id: 5, name: 'イベント' },
    { id: 6, name: '健康' },
    { id: 7, name: '友人・家族' },
    { id: 8, name: '財務管理' },
    { id: 9, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :messages

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/finishes_controller.rb
class FinishesController < ApplicationController
  def create
    finish = Finish.create(finish_params)
    if finish.save
      render json: { id: finish.id }, status: :created
    else
      render json: { errors: finish.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    finish = Finish.find(params[:id])
    if finish.destroy
      head :no_content
    else
      render json: { errors: finish.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def finish_params
    params.require(:finish).permit(:task_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # ログインしていないとき、ログインページへ遷移する
  before_action :authenticate_user!

  # 特定のgroupをparamsのidから取得
  before_action :find_group, except: :index

  # 編集権の制限
  before_action :only_current_user, only: :show

  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to new_task_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

  def find_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_name, :group_memo).merge(user_id: current_user.id)
  end

  def only_current_user
    return if current_user.id == @group.user.id

    redirect_to groups_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # ログインしていないとき、ログインページへ遷移する
  before_action :authenticate_user!

  # 全てのmessageを取得する
  before_action :messages_all, only: [:new, :create]

  def new
    @message = Message.new
  end

  def create
    # ユーザーとAIの双方のメッセージが正常に保存された時のみ完了する
    ActiveRecord::Base.transaction do
      # ユーザーのメッセージを保存
      user_message = Message.new(message_create_params)
      user_message.save!

      # ChatGptServiceでの処理
      user_message = message_create_params[:message]
      gpt = ChatGptService.new
      pronpts = gpt.chinese_room(@messages, user_message)

      # AIのメッセージを保存
      pronpts.each do |pronpt|
        gpt_message = Message.new(message: pronpt[:message], speaker: 1, message_type: pronpt[:message_type],
                                  user_id: current_user.id)
        gpt_message.save!
      end
    end
    redirect_to new_message_path
  end

  def update
    message = Message.find(params[:id])

    if message.update(message_update_params)
      redirect_to new_message_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    Message.where(user_id: current_user.id).destroy_all
    redirect_to new_message_path
  end

  private

  def messages_all
    @messages = Message.where(user_id: current_user.id)
  end

  def message_create_params
    params.require(:message).permit(:message).merge(user_id: current_user.id, speaker: 0, message_type: 0)
  end

  def message_update_params
    params.require(:message).permit(:message, :speaker, :message_type).merge(user_id: current_user.id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # ログインしていないとき、ログインページへ遷移する
  before_action :authenticate_user!

  # user.idを取得
  before_action :current_user_id

  # 特定のtaskをparamsのidから取得
  before_action :task_find, only: [:show, :update, :destroy]

  # 編集権の制限
  before_action :only_current_user, only: :show

  def index
    @tasks = Task.order("created_at DESC").where(user_id: @user)
  end

  def create
    @messages = Message.where(user_id: @user)

    todo = TodoRegistrationService.new(@messages, @user)
    todo.registration
    Message.where(user_id: @user).destroy_all

    redirect_to root_path
  end

  def show
  end

  def update
    if @task.update(task_params)
      redirect_to root_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def current_user_id
    @user = current_user.id
  end

  def only_current_user
    return if @user == @task.user_id

    redirect_to root_path
  end

  def task_find
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:group_id, :content, :memo, :type_id).merge(user_id: @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finishes_helper.rb
module FinishesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  # subjectで指定したmessage_typeがmessagesの中に存在しているか確認するメソッド
  def check_for_message_existence(messages, subject)
    judge = messages.select { |message| message.message_type == subject }
    !(judge == [])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/groups/index.html.erb
<%= render partial: "shared/header" %>
<main>
<% if user_signed_in? %>
  <div class="page_link_area">
    <div class="page_link_btn_container">
      <%= link_to "＜ タスク一覧", tasks_path, class:"page_link_btn" %>
    </div>
  </div>
  <h1 class="heading1">―― 全てのグループ ――</h1>
  <% @groups.each do |group| %>
    <%= render partial: "shared/group", locals: { group: group } %>
  <% end %>
<% end %>
</main>
<%= render partial: "shared/footer" %>

app/views/groups/show.html.erb
<%= render partial: "shared/header" %>
<main>
<% if user_signed_in? %>
  <div class="page_link_area">
    <div class="page_link_btn_container">
      <%= link_to "＜ すべてのグループ", groups_path, class:"page_link_btn" %>
    </div>
  </div>
  <h1 class="heading1">―― グループを編集 ――</h1>
  <div class="groups__show_form_container">
    <%= form_with model: @group, url:group_path, local: true, class:"groups__show_form" do |f| %>
      <div class="groups__show_label_area">
        <h3 class="groups__show_text_field_container">
          <%= f.text_field :group_name, placeholder:"概要を入力する（必須）", class:"groups__show_text_field" %>
        </h3>
      </div>
      <div class="groups__show_label_area">
        <div class="groups__show_text_area_container">
          <%= f.text_area :group_memo, placeholder:"メモを入力する", class:"groups__show_text_area" %>
        </div>      
      </div>
      <div class="groups__show_form_btn_area">
        <div class="action_btn_area">
          <%= f.submit "更新する", class:"update_action_btn" %>
        </div>
    <% end %>
        <div class="action_btn_area">
          <%= button_to "削除する", group_path(@group.id), method: :delete, class:"delete_action_btn" %>
        </div>
      </div>
  </div>
  <h1 class="heading1">―― グループのタスク ――</h1>
  <% @group.tasks.each do |task| %>
    <%= render partial: "shared/task", locals: { task: task } %>
  <% end %>
<% end %>
</main>
<%= render partial: "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Someday</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Noto Sans Japanese %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<%# 発言者がユーザーの場合 %>
<% if message.speaker == 0 %>
  <div class="message_area">
    <div class="speaker user"><%= username %></div>
    <div class="message_chat_area user">
      <div class="message_chat"><%= message.message %></div>
    </div>
  </div>

<%# 発言者がAIの場合 %>
<% elsif message.speaker == 1 %>
  <div class="message_area">
    <div class="speaker ai">AIアシスタント</div>
    <div class="message_chat_area">

      <%# 提案メッセージ %>
      <% if message.message_type == 1 || message.message_type == 3 %>
        <%= form_with model:message, url:message_path(message.id), local: true, class:"message_chat_form" do |f| %>
          <div class="message_chat_text_area_container">
            <%= f.text_area :message, class:"message_chat_text_area" %>
          </div>
          <div class="message_update_area">
            <%= f.submit "提案を修正", class:"update_action_btn" %>
          </div>
        <% end %>
      <%# 400番台メッセージ %>
      <% elsif message.message_type >= 400 %>
        <div class="message_chat message_type_400"><%= message.message %></div>
      <%# 300番台メッセージ %>
      <% elsif message.message_type >= 300 %>
        <div class="message_chat message_type_300"><%= message.message %></div>

      <%# その他のメッセージ %>
      <% else %>
        <div class="message_chat"><%= message.message %></div>
      <% end %>

    </div>
    <% if message.message_type == 1 %>
      <div class="message_supplement">AIからあなたへグループが提案されました！</div>
    <% elsif message.message_type == 3 %>
      <div class="message_supplement">AIからあなたへタスクが提案されました！</div>
    <% elsif message.message_type == 300 %>
      <%# <div class="message_supplement">※タスクを登録するにはもっと情報が必要です。</div> %>
    <% elsif message.message_type == 400 %>
      <div class="message_supplement">※タスクを考えるには、もっと具体的な情報が必要です。</div>
    <% end %>
  </div>
<% end %>

app/views/messages/new.html.erb
<%= render partial: "shared/header" %>
<main>
  <div class="page_link_area">
    <div class="page_link_btn_container">
      <%= link_to "＜ タスク一覧", tasks_path, class:"page_link_btn" %>
    </div>
  </div>
  <h1 class="heading1">―― チャット ――</h1>
  <div class="message_area">
    <div class="speaker">AIアシスタント</div>
    <div class="message_chat_area">
      <div class="message_chat">「困っていること」や「そのうちやろう」と思っていることはありませんか？</div>
    </div>
  </div>
  <% @messages.each do |message| %>
    <% unless message.message_type == 100 %>
      <%= render partial: "message", locals: { message: message, username: current_user.username } %>
    <% end %>
  <% end %>
  <div class="chat_action_container">
    <% unless @messages == [] %>
      <div class="chat_action_btn_area">
        <%= button_to "会話をリセット", message_path(@messages[0][:id]), method: :delete, class:"delete_action_btn" %>
      </div>
    <% end %>
    <% if check_for_message_existence(@messages, 3) %>
      <div class="chat_action_btn_area">
        <%= button_to "タスクを登録する", tasks_path, class:"new_action_btn" %>
      </div>
    <% end %>
  </div>
  <div class="underline"></div>
  <div class="message__new_form_area">
    <%= form_with model:@message, url:messages_path, local: true, class:"message__new_message_form" do |f| %>
      <div class="message__new_message_form_text_area_area">
        <%= f.text_area :message, placeholder:"メッセージを入力" ,class:"message__new_message_form_text_area" %>
      </div>
      <div class="message__new_message_form_submit_area">
        <%= f.submit "送信",class:"new_action_btn"%>
      </div>
    <% end %>
  </div>
</main>
<footer>
  <div class="footer__link_area"></div>
</footer>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer__link_area">
    <div class="footer__link_box">
      <% if user_signed_in? %>
        <%= link_to "タスクを考えて！", new_message_path, class: "footer__link_btn" %>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_group.html.erb
<div class="shared__group_area">
  <div class="shared__group_head_area">
    <h3 class="shared__group_name">・<%= group.group_name %></h3>
    <h3 class="shared__group_task_count"><%= group.tasks.count %></h3>
    <div class="shared__group_show_link_container">
      <%= link_to "＞", group_path(group.id), class: "shared__group_show_link_to square_link_btn"%>
    </div>
  </div>
  <div class="shared__group_memo_area">
    <div class="shared__group_memo"><%= group.group_memo %></div>
  </div>
  <div class="underline"></div>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="header__link_area">
    <div class="header__link_box">
      <h1 class="header__title">
        <%= link_to "ソノウチ", root_path, class:"header__title_link" %>
      </h1>
    </div>
    <div class="header__link_box left_shift">
      <div class="header__user_control_area">
      <% if user_signed_in? %>
        <div class="header__user_control_link_box">
          <div class="current_user"><%= "#{current_user.username}さん" %></div>
        </div>
        <div class="header__user_control_link_box">
          <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "header__user_control_link" %>
        </div>
      <% else %>
        <div class="header__user_control_link_box">
          <%= link_to "新規登録", new_user_registration_path, class: "header__user_control_link" %>
        </div>
        <div class="header__user_control_link_box">
          <%= link_to "ログイン", new_user_session_path, class: "header__user_control_link" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_task.html.erb
<div class="shared__task_area">
  <div class="shared__task_group_area">
    <div class="shared__task_group_container">
        <%= link_to "＞　#{task.group.group_name}", group_path(task.group.id), class:"shared__task_group_link_to" %>
    </div>
  </div>
  <div class="shared__task_content_area">
    <h1 class="shared__task_priority_container">
      <div class="shared__task_priority_area"><%= task.priority.weight %></div>
    </h1>
    <div class="shared__task_checkbox_label_container">
      <label class="finish_checkbox_label">
        <div class="finish_checkbox_container">
          <%= check_box_tag 'finish', task.id, task.finish.present?, {class: "finish_checkbox_box", data: { task_id: task.id,finish_id: task.finish&.id }} %>
          <span class="finish_checkbox-DummyInput"></span>
        </div>
        <h3 class="shared__task_content"><%= task.content %></h3>
      </label>
    </div>
    <div class="shared__task_show_link_container">
      <%= link_to "＞", task_path(task.id), class:"shared__task_show_link_to square_link_btn" %>
    </div>
  </div>
  <div class="shared__task_detail_area">
    <div class="shared__task_type nowrap"><%= task.type.name %></div>
    <div class="shared__task_hyphen">-</div>
    <div class="shared__task_memo"><%= task.memo %></div>
  </div>
  <div class="underline"></div>
</div>

app/views/tasks/index.html.erb
<%= render partial: "shared/header" %>
<main>
<% if user_signed_in? %>
  <div class="page_link_area">
    <div class="page_link_btn_container">
      <%= link_to "＞ すべてのグループ", groups_path, class:"page_link_btn" %>
    </div>
  </div>
  <h1 class="heading1">―― タスク一覧 ――</h1>
  <% @tasks.each do |task| %>
    <%= render partial: "shared/task", locals: { task: task } %>
  <% end %>
<% end %>
</main>
<%= render partial: "shared/footer" %>

app/views/tasks/show.html.erb
<%= render partial: "shared/header" %>
<main>
  <div class="page_link_area">
    <div class="page_link_btn_container">
      <%= link_to "＜ タスク一覧", tasks_path, class:"page_link_btn" %>
    </div>
  </div>
  <h1 class="heading1">―― タスクのグループ ――</h1>
  <%= render partial: "shared/group", locals: { group: @task.group } %>
  <h1 class="heading1">―― タスクの編集 ――</h1>
  <div class="task__show_priority_area">
    <div class="task__show_priority_container">
      <h1 class="task__show_priority"><%= @task.priority.weight %></h1>
    </div>
    <div class="task_show_priority_text">タスクの優先度は自動で設定されます</div>
  </div>
  <div class="tasks__show_form_area">
    <%= form_with model: @task, url:task_path, local: true, class:"tasks__show_form" do |f| %>
      <div class="tasks__show_label_area">
        <label class="finish_checkbox_label">
          <div class="finish_checkbox_container">
            <%= check_box_tag 'finish', @task.id, @task.finish.present?, {class: "finish_checkbox_box", data: { task_id: @task.id,finish_id: @task.finish&.id }} %>
            <span class="finish_checkbox-DummyInput"></span>
          </div>
          <h3 class="tasks__show_text_field_area">
            <%= f.text_field :content, placeholder:"タスクを入力する（必須）", class:"tasks__show_text_field" %>
          </h3>
        </label>
      </div>
      <div class="tasks__show_label_area">
        <label class="tasks__show_label">
          <div class="tasks__show_collection_select_area">
            <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"tasks__show_collection_select"}) %>
          </div>
        </label>
      </div>
      <div class="tasks__show_label_area">
        <div class="tasks__show_text_area_container">
          <%= f.text_area :memo, placeholder:"メモを入力する", class:"tasks__show_text_area" %>
        </div>
      </div>
      <div class="tasks__show_form_btn_area">
        <div class="action_btn_area">
          <%= f.submit "更新する", class:"update_action_btn" %>
        </div>
    <% end %>
        <div class="action_btn_area">
          <%= button_to "削除する", task_path(@task.id), method: :delete, class:"delete_action_btn" %>
        </div>
      </div>
  </div>
</main>
<%= render partial: "shared/footer" %>